name: pipeline CI/CD

env:
  dockerhub_repository: "tython0tyx/tython_dev"
  dockerhub_tag: "shortty"

on:
  push:
    branches:
      - main

jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ env.dockerhub_repository }}:${{ env.dockerhub_tag }} 
  deploy:
    needs: dockerhub-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROXMOX_HOST }}
          username: ${{ secrets.PROXMOX_USER }}
          key: ${{ secrets.PROXMOX_PASSWORD }}
          script: |
           ssh -i ~/.ssh/id_rsa_vm tybot@192.168.100.15 "
              echo '{
                 \"auths\": {
                  \"https://index.docker.io/v1/\": {
                   \"auth\": \"'\"$(echo -n \"$DOCKER_USERNAME:$DOCKER_PASSWORD\" | base64)\"'\"
                }
               }
             }' > ~/.docker/config.json && \
             cd /home/tybot/shortty
             sudo docker compose pull && \
             sudo docker compose up -d && \
             sudo docker image prune -f
             "
