name: pipeline CI/CD

env:
  dockerhub_repository: "tython0tyx/tython_dev"
  dockerhub_tag: "shortty"

on:
  push:
    branches:
      - main

jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ env.dockerhub_repository }}:${{ env.dockerhub_tag }} 
